#!/usr/bin/env bash
####################################
# general settings
####################################
WHITE="\033[1;37m"
GREEN="\033[32m"
BLUE="\033[34m"
CYAN="\033[36m"
NC="\033[0m"
RED="\033[31m"
####################################

SAIL_HOME="$HOME/.sail"
UPDATE_CHECK_TRACK_FILENAME="$SAIL_HOME/update-last-check"

####################################
# functions
####################################

function pull_sail() {
  mkdir -p "$SAIL_HOME/.source/"
  git clone -b main --single-branch git@github.com:bodyshopbidsdotcom/sail.git "$SAIL_HOME/.source/"
}

function install() {
  if pull_sail ; then
    sudo ln -s "$SAIL_HOME/.source/support/sail_exec" /usr/local/bin/sail
    touch "$UPDATE_CHECK_TRACK_FILENAME"
    echo -e "${BLUE}sail: ${GREEN}Success! ${NC}"
  fi
}

if [ "$(groups | grep -Ew "sudo|wheel|admin" >/dev/null)" ]; then
  install
else
  echo -e "${BLUE}sail: ${RED}You don't have local admin on this machine. Send IT a message in the #sail channel or submit a ticket! ${NC}"
fi
